//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSModel.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CSDBEntities : DbContext
    {
        public CSDBEntities()
            : base("name=CSDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cs_news> cs_news { get; set; }
        public virtual DbSet<cs_survey> cs_survey { get; set; }
        public virtual DbSet<cs_survey_answer> cs_survey_answer { get; set; }
        public virtual DbSet<cs_survey_answer_record> cs_survey_answer_record { get; set; }
        public virtual DbSet<cs_survey_record> cs_survey_record { get; set; }
        public virtual DbSet<cs_survey_topic> cs_survey_topic { get; set; }
        public virtual DbSet<cs_survey_user> cs_survey_user { get; set; }
        public virtual DbSet<cs_question> cs_question { get; set; }
        public virtual DbSet<cs_question_file> cs_question_file { get; set; }
    }
}
